spring.application.name=bunch

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/bunch
spring.datasource.username=bunch
spring.datasource.password=0001
spring.datasource.driver-class-name=org.postgresql.Driver
soring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# LIQUIBASE
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml